set(_CATKIN_CURRENT_PACKAGE "drone_visual_odometry")
set(drone_visual_odometry_VERSION "0.0.0")
set(drone_visual_odometry_MAINTAINER "lsi <lsi@todo.todo>")
set(drone_visual_odometry_PACKAGE_FORMAT "1")
set(drone_visual_odometry_BUILD_DEPENDS "cv3_bridge" "roscpp" "sensor_msgs" "std_msgs" "image_transport")
set(drone_visual_odometry_BUILD_EXPORT_DEPENDS "cv_bridge" "roscpp" "sensor_msgs" "std_msgs" "image_transport")
set(drone_visual_odometry_BUILDTOOL_DEPENDS "catkin")
set(drone_visual_odometry_BUILDTOOL_EXPORT_DEPENDS )
set(drone_visual_odometry_EXEC_DEPENDS "cv_bridge" "roscpp" "sensor_msgs" "std_msgs" "image_transport")
set(drone_visual_odometry_RUN_DEPENDS "cv_bridge" "roscpp" "sensor_msgs" "std_msgs" "image_transport")
set(drone_visual_odometry_TEST_DEPENDS )
set(drone_visual_odometry_DOC_DEPENDS )
set(drone_visual_odometry_URL_WEBSITE "")
set(drone_visual_odometry_URL_BUGTRACKER "")
set(drone_visual_odometry_URL_REPOSITORY "")
set(drone_visual_odometry_DEPRECATED "")